name: Publish SAM App

on:
  release:
    types: [published]

permissions:
  id-token: write  # required for requesting the JWT
  contents: read   # required for actions/checkout

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.135.0
    steps:
    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: Git clone
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Build site
      run: HUGO_ENV=production hugo --gc --minify
    - name: AWS login
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::891377039310:role/github-sar-publisher
        role-session-name: github-sar-publishing
        aws-region: eu-west-2
    - name: Build app
      run: |
        sam build
    - name: Package app
      run: |
        sam package --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-klxewohmcipf --output-template-file packaged.yaml
    - name: Publish app
      run: |
        sam publish --template packaged.yaml
